// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpCy-FUxkqkTCdwAhv_EAqtqHi5lQOP3c',
    appId: '1:866597882686:web:bae9f42b45f68a4bfeba6f',
    messagingSenderId: '866597882686',
    projectId: 'hunt-the-mafia',
    authDomain: 'hunt-the-mafia.firebaseapp.com',
    storageBucket: 'hunt-the-mafia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGPnuEUA0zlq6xEcMCc5tw4b7_excgEgc',
    appId: '1:866597882686:android:d792e769df69d2dafeba6f',
    messagingSenderId: '866597882686',
    projectId: 'hunt-the-mafia',
    storageBucket: 'hunt-the-mafia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmEhxyPEOfJ6DmnTh8QjAx3XUxqD9CPXE',
    appId: '1:866597882686:ios:d578f86a851746d4feba6f',
    messagingSenderId: '866597882686',
    projectId: 'hunt-the-mafia',
    storageBucket: 'hunt-the-mafia.appspot.com',
    androidClientId: '866597882686-mnou1v248r3esn15he08rjt1uvrtu6eh.apps.googleusercontent.com',
    iosClientId: '866597882686-hbq8gsqmto7kaprtp94oatjfqeitg8ol.apps.googleusercontent.com',
    iosBundleId: 'com.enhance.huntTheMafia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmEhxyPEOfJ6DmnTh8QjAx3XUxqD9CPXE',
    appId: '1:866597882686:ios:d578f86a851746d4feba6f',
    messagingSenderId: '866597882686',
    projectId: 'hunt-the-mafia',
    storageBucket: 'hunt-the-mafia.appspot.com',
    androidClientId: '866597882686-mnou1v248r3esn15he08rjt1uvrtu6eh.apps.googleusercontent.com',
    iosClientId: '866597882686-hbq8gsqmto7kaprtp94oatjfqeitg8ol.apps.googleusercontent.com',
    iosBundleId: 'com.enhance.huntTheMafia',
  );
}
